### PR TITLE
BR-42 Upgrade Maven version

### PR DESCRIPTION
**Pull request by TonyMorrison**
### Upgrade Maven version
The Maven version in the Jenkinsfile has been changed to maven-latest

### Testing 
This has been run on Jenkins
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/codice-parent_TM/job/master/ 

### Reviewers/Approvers
@shaundmorris 
@LinkMJB 
@bdeining

### CODE REVIEW

**Review by LinkMJB — CHANGES_REQUESTED** [review]
Not to muddy this up too much more, but it might be a good idea for us to enable PR builds while we are making changes to the Jenkinsfile

**Comment by shaundmorris** [comment]
Agree with @LinkMJB, @TonyMorrison is that something you can add in real quick or do we need another PR for that :-) ?

**Comment by TonyMorrison** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Review by shaundmorris — APPROVED** [review]

**Comment by TonyMorrison** [comment]
PR builds now enabled

**Review by LinkMJB — APPROVED** [review]

**Pull request merged**
